[Interface]
PrivateKey = kB7z0Jod0EduZvAHmoCGHofyKqFhSD8S2e7C72PsOXs=
Address = 10.66.66.3/24
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = rzwRcVRIu71rFlqBAUJfuvC9tw4Z6i2qn4DKKB9XpEI=
Endpoint = 47.82.0.187:443
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
